service: load-split-embed

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  memorySize: 128
  environment:
    RUNTIME: aws-lambda
  timeout: 900
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

package:
  exclude:
    - .npmignore
    - .vscode/**
    - .github/**
    - (*).json
    - (*).ipynb
    - node_modules/**
    - venv/**
    - LICENSE
    - test/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

functions:
  lse:
    handler: load_split_embed.handler
    # https://www.serverless.com/framework/docs/providers/aws/guide/functions#lambda-function-urls
    url: true
