service: load-split-embed

frameworkVersion: "3"

provider:
  name: aws
  # REF: https://www.serverless.com/blog/container-support-for-lambda
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  stage: ${env:STAGE, 'dev'}
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

functions:
  lse:
    image:
      name: appimage
    memorySize: 128
    environment:
      EMBEDDING_MODEL_URL: ${env:EMBEDDING_MODEL_URL}
      EMBEDDING_MODEL_KEY: ${env:EMBEDDING_MODEL_KEY}
      CHUNK_SIZE: 500
      CHUNK_OVERLAP: 20
    timeout:
      900
      # https://www.serverless.com/framework/docs/providers/aws/guide/functions#lambda-function-urls
    url: true
